global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "tgi"
    static_configs:
      - targets: ["tgi:8000"]

  - job_name: "nvidia-dcgm"
    static_configs:
      - targets: ["dcgm-exporter:9400"]
